[package]
name = "corpconftest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corpconf = { path = "../corpconf/" }
memmap = "0.6.2"
fs-err = "2.6.0"
